INPUT_DIR: "/images/"
MD_MODEL: "md_v4.1.0.pb"
IMG_FILE: 
MD_FILE: "md_out.json"
RECURSIVE: True
RELATIVE_FILENAMES: True
QUIET: False
IMAGE_QUEUE: False
THRESHOLD: 0.01
CHECKPOINT_FREQ: 100
CHECKPOINT_FILE: 
NCORES: 
